# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoformat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protoformat.proto\"\xaf\x01\n\x0b\x64\x61taRequest\x12\x0e\n\x06RFW_ID\x18\x01 \x01(\t\x12\x16\n\x0e\x62\x65nchmark_type\x18\x02 \x01(\t\x12\x13\n\x0bwork_metric\x18\x03 \x01(\t\x12\x12\n\nbatch_unit\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_ID\x18\x05 \x01(\x05\x12\x12\n\nbatch_size\x18\x06 \x01(\x05\x12\x11\n\tdata_type\x18\x07 \x01(\t\x12\x16\n\x0e\x64\x61ta_analytics\x18\x08 \x01(\t\"e\n\x0c\x64\x61taResponse\x12\x0e\n\x06RFW_ID\x18\x01 \x01(\t\x12\x15\n\rlast_batch_ID\x18\x02 \x01(\x05\x12\x16\n\nbatch_data\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x16\n\x0e\x64\x61ta_analytics\x18\x04 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoformat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATARESPONSE.fields_by_name['batch_data']._options = None
  _DATARESPONSE.fields_by_name['batch_data']._serialized_options = b'\020\001'
  _DATAREQUEST._serialized_start=22
  _DATAREQUEST._serialized_end=197
  _DATARESPONSE._serialized_start=199
  _DATARESPONSE._serialized_end=300
# @@protoc_insertion_point(module_scope)
